steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-react-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-react-app:$SHORT_SHA'
      ]

  # Step 3: Update image in Kubernetes deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/react-app',
        'react-app=us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-react-app:$SHORT_SHA'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-standard-cluster'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-react-app:$SHORT_SHA'