# Cloud Build: Build → Push → Deploy to GKE (Standard cluster, us-central1)

substitutions:
  _REGION: us-central1
  _REPO: my-docker-repo
  _IMAGE: my-react-app
  _CLUSTER: my-gke-standard-cluster
  _LOCATION: us-central1
  _NAMESPACE: default

steps:
  # 1) Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
      - .

  # 2) Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'

  # 3) Auth to GKE & update Deployment image (single step to keep kubecontext)
  - name: gcr.io/google.com/cloudsdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gcloud --quiet components install gke-gcloud-auth-plugin || true
        gcloud container clusters get-credentials "${_CLUSTER}" --region "${_LOCATION}" --project "$PROJECT_ID"
        kubectl -n "${_NAMESPACE}" set image deployment/react-app \
          react-app="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:$SHORT_SHA"
        kubectl -n "${_NAMESPACE}" rollout status deploy/react-app --timeout=180s

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'