apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  annotations:
    # Internal TCP/UDP Load Balancer on GKE
    cloud.google.com/load-balancer-type: "Internal"
    # Optional: allow access from other regions via VPC (keep false if not needed)
    # networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80