apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer   # Exposes via GCP Load Balancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80