apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer   # <-- external LB
  selector:
    app: react-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
