name: ci-cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: entry-241907
  GCP_REGION: us-central1
  AR_REPO: my-docker-repo
  IMAGE_NAME: my-react-app
  GKE_CLUSTER: my-gke-cluster         # <-- from Terraform outputs
  GKE_LOCATION: us-central1           # <-- regional cluster

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.compute_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag (short SHA)
        id: compute_tag
        run: echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_GKE_SA }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.IMAGE_NAME }}:${{ steps.compute_tag.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_GKE_SA }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}

      - name: Update image tag in deployment
        run: |
          TAG="${{ needs.build_and_push.outputs.tag }}"
          sed -i "s|my-react-app:TAG|my-react-app:${TAG}|g" k8s/deployment.yml

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl rollout status deploy/react-app --timeout=180s

      - name: Show service
        run: kubectl get svc react-app-service -o wide